### ISSUE TITLE
Python 3.2 Support

### ISSUE THREAD

**Issue by timogasda** [hpi-epic/pyHANA#2]
We currently do not support Python 3.2 because specifically this version has dropped support for the `u''` unicode string literal.

We have not found a suitable solution yet, so Python 3.2 support is hereby **postponed**.

**Comment by hugovk** [comment]
I think it's safe to drop it entirely, it's been EOL since 2016-02-27 and most of the most-downloaded packages have also dropped it. 

https://en.wikipedia.org/wiki/CPython#Version_history
https://hugovk.github.io/drop-python/3.2/

**Comment by Bouncner** [comment]
Timo, should we close it? Don't see a reason to further have that issue open.

**Comment by timogasda** [comment]
Sure, you rarely come across Python 3.2 these days anyway
